USE ROLE CREDITPULSE_ENGINEER_ROLE;
USE WAREHOUSE CREDITPULSE_WH;
USE DATABASE CREDITPULSE;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS SEC_COMPANY_FACTS (
    INGESTION_ID VARCHAR NOT NULL,
    BATCH_ID VARCHAR NOT NULL,

    CIK VARCHAR NOT NULL,
    ENTITY_NAME VARCHAR,

    SOURCE_URL VARCHAR NOT NULL,
    FETCHED_AT TIMESTAMP_TZ NOT NULL,

    PAYLOAD_HASH VARCHAR NOT NULL,
    RAW_PAYLOAD VARIANT NOT NULL,

    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Raw SEC Company Facts API responses preserved as source-aligned JSON payloads.';