name: "creditpulse"
version: "1.0.0"
config-version: 2

profile: "creditpulse"

model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  creditpulse:
    staging:
      +materialized: view
      +schema: CORE

    intermediate:
      +materialized: view
      +schema: CORE

    marts:
      +materialized: table
      +schema: ANALYTICS